insert into javaprobe_apprule (applicationrule,applicationname) values ('io.vertx.core.Launcher','Vertx');
insert into javaprobe_apprule (applicationrule,applicationname) values ('backtype.storm.daemon.supervisor','Storm');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.sonatype.nexus.bootstrap.jsw.JswLauncher','Sonatype.Nexus');
insert into javaprobe_apprule (applicationrule,applicationname) values ('play.core.server','Play FrameWork');
insert into javaprobe_apprule (applicationrule,applicationname) values ('com.mediav.warpdrive.ScribeKafkaProducer','Media Warpdrive');
insert into javaprobe_apprule (applicationrule,applicationname) values ('com.zendesk.maxwell.Maxwell','Zendesk Xaxwell');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.logstash.Logstash','Logstash');
insert into javaprobe_apprule (applicationrule,applicationname) values ('KafkaOffsetChecker.jar','KafakaOffsetChecker');
insert into javaprobe_apprule (applicationrule,applicationname) values ('kafka.tools.MirrorMaker','Kafka MirroMaker');
insert into javaprobe_apprule (applicationrule,applicationname) values ('kafka.Kafka,','Kafka');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.jruby.Main','Jruby');
insert into javaprobe_apprule (applicationrule,applicationname) values ('sun.tools.jps.Jps','Sun Jps');
insert into javaprobe_apprule (applicationrule,applicationname) values ('queryJersey','queryJersey');
insert into javaprobe_apprule (applicationrule,applicationname) values ('jenkins.war','jenkins');
insert into javaprobe_apprule (applicationrule,applicationname) values ('jeety/start.jar','Jeety');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.tanukisoftware.wrapper.WrapperSimpleApp','Java Service Wapper');
insert into javaprobe_apprule (applicationrule,applicationname) values ('jmx_prometheus_httpserver','Jmx_exporte');
insert into javaprobe_apprule (applicationrule,applicationname) values ('graylog.jar','Graylog');
insert into javaprobe_apprule (applicationrule,applicationname) values ('com.baidu.sos.HadoopVFS4','Baidu.SOS');
insert into javaprobe_apprule (applicationrule,applicationname) values ('azkaban.','Azkaban');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.zookeeper','Apache Zookeeper');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.catalina.startup.Bootstrap','Apache Tomcat');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.storm.','Apache Storm');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.spark','Apache spark');
insert into javaprobe_apprule (applicationrule,applicationname) values ('ApacheJMeter.jar','Apache JMeter');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.flume.node.Application','Apache flume');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.flink.runtime.taskexecutor.TaskManagerRunner','Apache flink');
insert into javaprobe_apprule (applicationrule,applicationname) values ('io.druid.cli.Main','Apache druid');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.druid.cli.Main','Apache druid');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.doris.PaloFe','Apache doris');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.tools.ant.launch.Launcher','Apache ant');
insert into javaprobe_apprule (applicationrule,applicationname) values ('org.apache.hadoop.','Apache Hadoop');

